#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x3DBFB6882C9358FB (info@kdab.com)
#
Name     : kdsoap
Version  : 1.9.0
Release  : 1
URL      : https://github.com/KDAB/KDSoap/releases/download/kdsoap-1.9.0/kdsoap-1.9.0.tar.gz
Source0  : https://github.com/KDAB/KDSoap/releases/download/kdsoap-1.9.0/kdsoap-1.9.0.tar.gz
Source1  : https://github.com/KDAB/KDSoap/releases/download/kdsoap-1.9.0/kdsoap-1.9.0.tar.gz.asc
Summary  : Qt-based client-side and server-side SOAP component
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0+
Requires: kdsoap-bin = %{version}-%{release}
Requires: kdsoap-data = %{version}-%{release}
Requires: kdsoap-lib = %{version}-%{release}
Requires: kdsoap-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : buildreq-qmake

%description
KDSoap can be used to create client applications for web services
and also provides the means to create web services without the need
for any further component such as a dedicated web server.

Authors:
--------
      Klaralvdalens Datakonsult AB (KDAB) <info@kdab.com>

%package bin
Summary: bin components for the kdsoap package.
Group: Binaries
Requires: kdsoap-data = %{version}-%{release}
Requires: kdsoap-license = %{version}-%{release}

%description bin
bin components for the kdsoap package.


%package data
Summary: data components for the kdsoap package.
Group: Data

%description data
data components for the kdsoap package.


%package dev
Summary: dev components for the kdsoap package.
Group: Development
Requires: kdsoap-lib = %{version}-%{release}
Requires: kdsoap-bin = %{version}-%{release}
Requires: kdsoap-data = %{version}-%{release}
Provides: kdsoap-devel = %{version}-%{release}
Requires: kdsoap = %{version}-%{release}
Requires: kdsoap = %{version}-%{release}

%description dev
dev components for the kdsoap package.


%package doc
Summary: doc components for the kdsoap package.
Group: Documentation

%description doc
doc components for the kdsoap package.


%package lib
Summary: lib components for the kdsoap package.
Group: Libraries
Requires: kdsoap-data = %{version}-%{release}
Requires: kdsoap-license = %{version}-%{release}

%description lib
lib components for the kdsoap package.


%package license
Summary: license components for the kdsoap package.
Group: Default

%description license
license components for the kdsoap package.


%prep
%setup -q -n kdsoap-1.9.0
cd %{_builddir}/kdsoap-1.9.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1587737572
mkdir -p clr-build
pushd clr-build
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1587737572
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kdsoap
cp %{_builddir}/kdsoap-1.9.0/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/kdsoap/ff3ed70db4739b3c6747c7f624fe2bad70802987
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kdwsdl2cpp

%files data
%defattr(-,root,root,-)
/usr/share/mkspecs/features/kdsoap.prf

%files dev
%defattr(-,root,root,-)
/usr/include/KDSoapClient/KDDateTime
/usr/include/KDSoapClient/KDDateTime.h
/usr/include/KDSoapClient/KDQName
/usr/include/KDSoapClient/KDQName.h
/usr/include/KDSoapClient/KDSoap
/usr/include/KDSoapClient/KDSoap.h
/usr/include/KDSoapClient/KDSoapAuthentication
/usr/include/KDSoapClient/KDSoapAuthentication.h
/usr/include/KDSoapClient/KDSoapClient
/usr/include/KDSoapClient/KDSoapClientInterface
/usr/include/KDSoapClient/KDSoapClientInterface.h
/usr/include/KDSoapClient/KDSoapEndpointReference
/usr/include/KDSoapClient/KDSoapEndpointReference.h
/usr/include/KDSoapClient/KDSoapFaultException
/usr/include/KDSoapClient/KDSoapFaultException.h
/usr/include/KDSoapClient/KDSoapGlobal
/usr/include/KDSoapClient/KDSoapGlobal.h
/usr/include/KDSoapClient/KDSoapHeaders
/usr/include/KDSoapClient/KDSoapJob
/usr/include/KDSoapClient/KDSoapJob.h
/usr/include/KDSoapClient/KDSoapMessage
/usr/include/KDSoapClient/KDSoapMessage.h
/usr/include/KDSoapClient/KDSoapMessageAddressingProperties
/usr/include/KDSoapClient/KDSoapMessageAddressingProperties.h
/usr/include/KDSoapClient/KDSoapNamespaceManager
/usr/include/KDSoapClient/KDSoapNamespaceManager.h
/usr/include/KDSoapClient/KDSoapPendingCall
/usr/include/KDSoapClient/KDSoapPendingCall.h
/usr/include/KDSoapClient/KDSoapPendingCallWatcher
/usr/include/KDSoapClient/KDSoapPendingCallWatcher.h
/usr/include/KDSoapClient/KDSoapSslHandler
/usr/include/KDSoapClient/KDSoapSslHandler.h
/usr/include/KDSoapClient/KDSoapUdpClient
/usr/include/KDSoapClient/KDSoapUdpClient.h
/usr/include/KDSoapClient/KDSoapValue
/usr/include/KDSoapClient/KDSoapValue.h
/usr/include/KDSoapClient/KDSoapValueList
/usr/include/KDSoapServer/KDSoapDelayedResponseHandle
/usr/include/KDSoapServer/KDSoapDelayedResponseHandle.h
/usr/include/KDSoapServer/KDSoapServer
/usr/include/KDSoapServer/KDSoapServer.h
/usr/include/KDSoapServer/KDSoapServerAuthInterface
/usr/include/KDSoapServer/KDSoapServerAuthInterface.h
/usr/include/KDSoapServer/KDSoapServerCustomVerbRequestInterface
/usr/include/KDSoapServer/KDSoapServerCustomVerbRequestInterface.h
/usr/include/KDSoapServer/KDSoapServerGlobal
/usr/include/KDSoapServer/KDSoapServerGlobal.h
/usr/include/KDSoapServer/KDSoapServerObjectInterface
/usr/include/KDSoapServer/KDSoapServerObjectInterface.h
/usr/include/KDSoapServer/KDSoapServerRawXMLInterface
/usr/include/KDSoapServer/KDSoapServerRawXMLInterface.h
/usr/include/KDSoapServer/KDSoapThreadPool
/usr/include/KDSoapServer/KDSoapThreadPool.h
/usr/lib64/cmake/KDSoap/KDSoapConfig.cmake
/usr/lib64/cmake/KDSoap/KDSoapConfigVersion.cmake
/usr/lib64/cmake/KDSoap/KDSoapMacros.cmake
/usr/lib64/cmake/KDSoap/KDSoapTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KDSoap/KDSoapTargets.cmake
/usr/lib64/libkdsoap-server.so
/usr/lib64/libkdsoap.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/KDSoap/LICENSE.GPL.txt
/usr/share/doc/KDSoap/LICENSE.txt
/usr/share/doc/KDSoap/README.txt
/usr/share/doc/KDSoap/kdsoap.pri
/usr/share/doc/KDSoap/kdwsdl2cpp.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libkdsoap-server.so.1.9.0
/usr/lib64/libkdsoap.so.1.9.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kdsoap/ff3ed70db4739b3c6747c7f624fe2bad70802987
